### PR TITLE
pynsq and asyncio together

### PR DESCRIPTION
**Pull request by vortex14**
Many people use asyncio to work in python 3, added 2 new examples to help understand.

### CODE REVIEW

**Comment by mreiferson** [comment]
Thanks for this, let's add the example source, but I don't think we need the update in the README. The CI linter is also complaining about trailing newlines...

**Comment by vortex14** [comment]
> Thanks for this, let's add the example source, but I don't think we need the update in the README. The CI linter is also complaining about trailing newlines...

Already rollbacked README.md

**Comment by mreiferson** [comment]
Great, would you mind squashing these commits down to one, please?

**Comment by vortex14** [comment]
> Great, would you mind squashing these commits down to one, please?

ready !

**Pull request merged**
