### PR TITLE
PeriodicCallback: remove io_loop argument for tornado v5 compatibility

### PR DESCRIPTION
**Pull request by jehiah**
This removes the io_loop argument from `PeriodicCallback` for tornado v5 forwards compatibility.

WIP: This should ideally get tested against tornadov5 but i'm not sure an easy way to do that since it's not released yet. Also i'm not sure this is the complete set of changes needed yet.

```
Traceback (most recent call last):
  File "queuereader_events.py", line 32, in <module>
    only_include_hosts=settings.get('nsqd_silod_on_staging'),
  File "/.../local/lib/python2.7/site-packages/libbitly/NSQReader.py", line 77, in __init__
    super(Reader, self).__init__(*args, **kwargs)
  File "/.../local/lib/python2.7/site-packages/nsq/reader.py", line 159, in __init__
    super(Reader, self).__init__(**kwargs)
  File "/.../local/lib/python2.7/site-packages/nsq/client.py", line 19, in __init__
    io_loop=self.io_loop).start()
TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

### CODE REVIEW

**Comment by mreiferson** [comment]
You're upgrading to Tornado 5 already 😳 😁

**Comment by jehiah** [comment]
I don't have time to push this forward, but i've rebased it. 

It looks like the primary issues are just test related because you can't specify the ioloop for PeriodicCallback which we leveraged for testing. cc: @ploxiln

**Comment by ploxiln** [comment]
I plan to tackle this soon.

**Comment by aaronjheng** [comment]
Any plans ?

**Comment by ploxiln** [comment]
yes, plans ... quite delayed plans apparently, sorry about that ...

**Comment by ploxiln** [comment]
superseded by #232

**Pull request closed without merging**
